FROM python:3.11-slim

WORKDIR /app

COPY app.py .
COPY requirements_ui.txt .

RUN pip install -r requirements_ui.txt

EXPOSE 7860

CMD ["streamlit", "run", "app.py", "--server.port=7860", "--server.address=0.0.0.0"]
